AEAT_ERRORS = [
    (None, ''),
    ('3501', 'Technical error of BBDD'),
    ('3500', 'Technical error of BBDD. Error in the Integrity of the Information'),
    ('3502', 'Technical error. Failed to get invoice data'),
    ('3503', 'Invoice consulted for the provision of Payments / Collections does not exist'),
    ('3504', 'Technical error. Failed to get Metall Collection data'),
    ('3505', 'Technical error. Error obtaining the data of the Insurance Operation'),
    ('4100', 'Error in header. The contents of the IDVersionSii field are invalid.'),
    ('4101', 'Error in header. The content of theCommunication field is invalid.'),
    ('4102', 'XML does not meet the schema. Required field is missing: XXXX'),
    ('4103', 'Unexpected error parsing the XML'),
    ('4104', 'Error in header. The value of the NIF field of the Holder block is not identified'),
    ('4105', 'Error in the header. The value of the NIFRepresentator field of the Holder block is not identified'),
    ('4106', 'Error in date format'),
    ('4107', 'Technical error when obtaining the CSV.'),
    ('4108', 'The XML root tag does not match the defined schema'),
    ('4109', 'NIF is not identified. NIF: XXXX'),
    ('4110', 'Failed to get the certificate.'),
    ('4111', 'The NIF is in the wrong format.'),
    ('4112', 'Technical error checking powers.'),
    ('4113', 'Technical error when creating the process.'),
    ('4114', 'The holder of the certificate must be the holder of the book of registry, social worker or proxy'),
    ('4115', 'Technical error checking Social Collaboration.'),
    ('4116', 'The allowed limit of registrations for the block DatosInmueble / DetalleIVA has been exceeded'),
    ('4117', 'XML does not meet the schema. The maximum allowable invoice threshold has been exceeded to register.'),
    ('4118', "The holder's NIF is not authorized to send information to the system. You must register previously"),
    ('4122', "Error in the header. The holder's NIF has an incorrect format."),
    ('4123', 'Error in header. The NIFRepresentant has an incorrect format.'),
    ('4124', 'Error The address does not correspond to the input file.'),
    ('4125', 'XML does not meet the schema. The maximum allowable amount of operations has been exceeded to register.'),
    ('1100', "Incorrect value or field type: XXXX"),
    ('1101', "Incorrect field code value"),
    ('1102', "Field Value Incorrect Period"),
    ('1103', "Incorrect IDType field value"),
    ('1104', "Incorrect ID field value"),
    ('1105', "Field Value NumberFactory Incorrect Enumerator"),
    ('1106', "Field Value DateExpeditionInvoiceIssuer Incorrect"),
    ('1107', "Field Value Type Invoice Incorrect"),
    ('1108', "Field Value Location Property Incorrect"),
    ('1109', "Field Value Key Special Regime or Incorrect Transcendence"),
    ('1110', "Field Value Payment Medium or Incorrect Collection"),
    ('1111', "Field Value Type Incorrect Amending"),
    ('1112', "The invoice NIF must be the same as the NIF of the record holder"),
    ('1113', "Field Value CauseExcluded Incorrect"),
    ('1114', "Incorrect type field value"),
    ('1115', "If the invoice has part No Subject must report at least one of the two amounts not subject"),
    ('1116', "NIF is not identified. NIF: XXXXX"),
    ('1117', "NIF is not identified. NIF: XXXXX. NAME_RACE: YYYYY"),
    ('1118', "The Issuer's Country Code and the Counterparty's Country Code do not match"),
    ('1119', "The IdType of the Issuer and the Counterpart do not match"),
    ('1120', "Issuer and Counterparty ID do not match"),
    ('1121', "The Issuer's and Counterpart's NIF do not overlap"),
    ('1122', "In the case of a minor, the NIF of the representative must contain value"),
    ('1123', "In case of a minor, the NIF of the representative can not coindidir with the NIF of the holder"),
    ('1124', "Country Code is mandatory when Type Identification is different from VAT NIF"),
    ('1125', "The Expedition Date is greater than the current date"),
    ('1126', "Field value Incorrect exercise. This should be the current or previous year"),
    ('1127', "Invoice Type of Seats Summary, NumberStockFactorEmisterSummaryFin is undeclared"),
    ('1128', "Invoice type is not Seats Summary and has NumSeriesFactorSamplingResumedFin declared"),
    ('1129', "The IssuedForColors field only accepts N or S values"),
    ('1130', "Field Value TypeCommunication Incorrect."),
    ('1131', "Field value IncorrectKeyword."),
    ('1132', "Field value StateMember is incorrect."),
    ('1133', "Incorrect IDType field value. Must have value 02"),
    ('1134', "If the invoice is of the rectifying type, the TypeRectificative field must have value."),
    ('1135', "If the invoice is not an amendment type, the TypeRectificative field must have no value."),
    ('1136', "The field Invoices should be reported only if the invoice is invoice type issued in Replacement of invoiced and declared simplified invoices."),
    ('1137', "If the invoice is not of the Amending or Summary Invoice type, the field Refunded Bills can not be informed."),
    ('1138', "If the invoice is an Amending amendment, the rectification amount is mandatory"),
    ('1139', "If the invoice is not an Amending Amendment or an Invoice Summary ReCotification block must have no value"),
    ('1140', "The transactions may have within the subject part, exempt part and / or non exempt part. So, Only one block or both may appear, but at least one (Exempt and / or Exempt)"),
    ('1141', "The operations may have part subject and part not subject. Therefore, only one Block or both, but at least one must appear (Subject and / or No subject)"),
    ('1142', "Field Value NumberNumberFactorEmisterRemand Incorrect"),
    ('1143', "Field value NIF of block IDFacture with incorrect type"),
    ('1144', "The invoice ID and CounterSource fields of the invoice are different"),
    ('1145', "Field value Incorrect period. This must be less than or equal to the current period"),
    ('1146', "The CodigoPais field indicated for the identification of NIF-IVA does not coincide with the two First characters of ID"),
    ('1147', "Error in the IDFactura block. IncorrectNameName field value."),
    ('1148', "BreakdownTypeOperation needs at least ProvisionServices or Delivery or both"),
    ('1149', "The field ID is not identified"),
    ('1150', "The field CodePais indicated does not match the first two digits of the identifier"),
    ('1151', "The value 03 can only be entered in the Medium field when the Date of payment / payment '31 -12 'for the year"),
    ('1152', "If the field Average has 03 value the field Account_O_Medium can not have value"),
    ('1153', "NIF is formatted incorrectly"),
    ('1154', "The field MiscellaneousDisitors only accepts N or S values"),
    ('1155', "The Cadastral Reference field must be informed whenever the FieldInput field does not Has value 3"),
    ('1156', "Field value KeyOperation is not included in the list of allowed values"),
    ('1157', "The BreakdownFactory block must have reported at least one of the two blocks InvestmentPayment or Deferred Transfer"),
    ('1158', "The Counterpart field must be informed as long as the TypeFactor field has no value F2 or F4"),
    ('1159', "The Coupon field only accepts N or S values"),
    ('1160', "If the invoice is not of the type Invoice Amending in simplified invoices or summary entry, the Coupon field should have no value"),
    ('1166', ""),
    ('1177', "The value of the field XXX is not among the allowed values"),
    ('3000', "Duplicate Invoice"),
    ('3001', "Registration is already unsubscribed"),
    ('3002', "There is no record"),
    ('3003', "Can not Include Charges for Unsubscribed Bills"),
    ('3004', "Maximum field size exceeded"),
    ('3005', "Collections can not be included if the field KeyRegimenSpecialTotal of the invoice Has a value other than 07"),
    ('3006', "Payment of unsubscribed invoices can not be included"),
    ('3007', "You can not include payments if the fieldTypeRegistryType of the invoice field Has a value other than 07"),
    ('3008', "There is already a Metallic Collection with this Counterpart"),
    ('3009', "Duplicate intra-Community operation"),
    ('3010', "The Presenter does not have the necessary permissions to update this invoice"),
    ('3011', "It is not allowed to modify the Special Regime Key in invoices that contain Collections or Payments"),
    ('3012', "There is already an Insurance Operation with this Counterparty"),
    ('2000', "If the fieldTypeRegistryType has a value of 12 or 13 the block of DatosInmueble must be informed"),
    ('2001', "The base fieldAvailableAvailable on invoices issued should not be reported if the field ClaveRegimenEspecialTrascendencia has a value other than 06"),
    ('2002', "Error if SpecialRegimenKeyTransfer different from 12, 13 and the block of Estate"),
    ('2003', "Some of the rectified invoices do not exist in the system"),
    ('2004', "Technical Error when consulting the list of rectified invoices"),
    ('2005', "The BaseAvailableAccount field should not be reported on received invoices if the field ClaveRegimenEspecialTrascendencia has a value other than 06"),
    ('2006', "The invoice contains a breakdown at the invoice level when it corresponds to a breakdown at the Transaction, since it is a non-simplified invoice or summary statement and the counterpart contains a IdOtro or a NIF beginning with N"),
    ('2007', "The Total Amount field is not more than 6,000"),
    ('2008', "The field PercentDeliveryREAGYP should not be reported if the field KeyRegimenSpecialTrading on invoices received has a value other than 02"),
    ('2009', "Do not enter the field PaymentCompensationREAGYP if the field KeyRegimenSpecialTrading on invoices received has a value other than 02"),
    ('2011', "Counterpart NIF is not in the Census"),
]
