[build-system]
requires = ["flit_core >=2,<4", "pydantic==1.8.2", "google-cloud-firestore==2.1.3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "faststore"
author = "Sarmad Gulzar"
author-email = "sarmadgulzar@hotmail.com"
home-page = "https://github.com/sarmadgulzar/faststore"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

