#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['faststore']

package_data = \
{'': ['*']}

setup(name='faststore',
      version='0.1.2',
      description='Faster development using Firestore',
      author='Sarmad Gulzar',
      author_email='sarmadgulzar@hotmail.com',
      url='https://github.com/sarmadgulzar/faststore',
      packages=packages,
      package_data=package_data,
     )
