
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T17:54:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "76850debe989b63400618a8e34e6943e8bc6197f",
 "version": "0.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
