
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T12:16:11+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "384b1b14d0aeb735f34de28ac3e19aa4db43d46c",
 "version": "1.34.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
