
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T19:21:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc9d01b6f7e5b5a76c570cd1aeb7d2a3e209c71d",
 "version": "6.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
