repos:
- repo: https://github.com/psf/black
  rev: 21.6b0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.9.2
  hooks:
    - id: isort

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
