
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T18:14:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d5b36e5c6bfff90414def96e46849a6b58e532d",
 "version": "0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
