
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T09:06:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c160f34f1c773a927c9e944f727003cbd185dee5",
 "version": "1.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
