[tool.poetry]
name = "thlink-backend-deployment"
version = "0.6.0"
description = ""
authors = ["thlink"]

[tool.poetry.dependencies]
python = "^3.7"
"aws-cdk.core" = "^1.105.0"
"aws-cdk.aws-lambda" = "^1.105.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
