import argparse
from .classes.telemetry_server import TelemetryServer as TelemetryServer

def entry(args: argparse.Namespace) -> int: ...
def add_app_args(parser: argparse.ArgumentParser) -> None: ...
