
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T16:52:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ecf4a60d425ea1106f0490d1f18c22912071591",
 "version": "0.13.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
