#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['dategen']

package_data = \
{'': ['*']}

setup(name='dategen',
      version='0.1',
      description='A datetime generator, backward from yesterday.',
      author='cmc2',
      author_email='changming.chen.1970@gmail.com',
      url='http://none',
      packages=packages,
      package_data=package_data,
     )
