
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T14:46:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3be84f3a9a47ea229e61a37581c35c8cae26052a",
 "version": "4.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
