# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://So-Cool.github.io/xpose/"

git_url = "https://github.com/So-Cool/xpose/tree/master/"

def custom_doc_links(name): return None
