
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T16:39:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d1f1de8256522847fccbc33cd50f12a4ef69cac",
 "version": "v0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
