
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T23:06:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d34f624fcb30f24fb4e7e7d9aa71f29d82afb265",
 "version": "v1.1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
