
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T16:58:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd6e6b2c55e1a7010a664bffca2173317276613b",
 "version": "6.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
