
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-17T07:58:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d99a91cd2b43121ae86c5a8f3653eb4952f6c93",
 "version": "1.10.0.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
