
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T12:04:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4bee138ea88f0091611debde7cd6ba7ee560444",
 "version": "0.7.0.post.dev278"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
