[tool.poetry]
name = "python-sourcery"
version = "0.0.0"
description = "Various extractors that generate a SQLite database (with tricks)"
authors = ["Amirouche <amirouche@hyper.dev>"]
license = "Apache-2.0"
packages = [
    { include = "sourcery" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
