#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['wtpython']

package_data = \
{'': ['*'], 'wtpython': ['backends/*']}

install_requires = \
['parse == 1.19.0',
 'requests == 2.25.1',
 'textual == 0.1.7',
 'toml == 0.10.2',
 'rich == 10.6.0',
 'pyperclip == 1.8.2',
 'requests-cache == 0.7.1',
 'markdownify == 0.9.2']

extras_require = \
{'dev': ['pre-commit >= 2.13.0'],
 'test': ['flake8~=3.7',
          'flake8-annotations~=2.0',
          'flake8-bandit~=2.1',
          'flake8-docstrings~=1.5',
          'flake8-isort~=4.0',
          'isort~=5.9',
          'pytest >= 6.2.4',
          'pytest-cov >= 2.12.1',
          'pytest-datadir >= 1.3.1',
          'pytest-randomly >= 3.8.0']}

entry_points = \
{'console_scripts': ['wtpython = wtpython.__main__:main']}

setup(name='wtpython',
      version='0.1',
      description='wtpython',
      author='what-the-python team',
      author_email='email@example.com',
      url='https://github.com/what-the-python/wtpython',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.9',
     )
