# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/models.slope_graph.ipynb (unless otherwise specified).

__all__ = ['SlopeGraphModel']

# Cell
from ..mvc import Model
from traitlets import Unicode, List

# Cell
class SlopeGraphModel(Model):

    title = Unicode()
    xvar = Unicode()
    ylabel = Unicode()
    names = List()
    values = List()
    xs = List()
    ys = List()
    plot_status = Unicode()

    def __init__(self, title, xvar, dep_var, names, values):
        self.title = title
        self.xvar = xvar
        self.ylabel = dep_var
        self.names = names
        self.values = values
        self.setLanding()

    def setLanding(self):
        for i in range(len(self.names)):
            self.xs.append([-1.0, 1.0])
            self.ys.append([0, 0])