
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:31:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1ede420f6db24486d78ab63d5eb6f2b77275fc8",
 "version": "0.7.0.post.dev272"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
