
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T12:07:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b03ee5180f4c9759dda3048e14ec875b56f15407",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
