
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T06:12:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cda2d5ae9dea7dab938912030d2176e3ee0c8dcb",
 "version": "0.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
