
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T10:00:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "146175a595e2b84a60b1fade2e25886bd3701ba9",
 "version": "0.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
