"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Trace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    TOUCHES_FIELD_NUMBER: builtins.int
    id: typing.Text = ...

    @property
    def touches(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraceTouch]: ...

    def __init__(self,
        *,
        id : typing.Text = ...,
        touches : typing.Optional[typing.Iterable[global___TraceTouch]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"id",b"id",u"touches",b"touches"]) -> None: ...
global___Trace = Trace

class TraceTouch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    time: builtins.int = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        time : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"time",b"time"]) -> None: ...
global___TraceTouch = TraceTouch
