
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T12:43:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c18d1cf26e7a28dca86b1d3083be526e2c6d3d9",
 "version": "0.0.73"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
