
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T14:38:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d289c4cdd48f80406e6beb0f82ea37dd992228a4",
 "version": "0.13.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
