
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T20:12:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf78399bff63bda3010dd904c5bc112c5f72fc64",
 "version": "0.8.13b0.dev202107200711"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
