
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T14:57:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a4fa9a889491acfd2488afdac350c3fd4d55808",
 "version": "2021.07.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
