
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T11:15:24+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "191bd1ca2fdec8ada545072b6e83b585cc51e3dd",
 "version": "0.7.0.post.dev290"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
