
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T12:34:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f597ae7350bb01c9bd881d7e1dd58fdade02d6d",
 "version": "0.9.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
