[tool.poetry]
name = "kiez"
version = "0.2.0"
description = "Hubness reduced nearest neighbor search for entity alignment with knowledge graph embeddings"
authors = ["Daniel Obraczka <obraczka@informatik.uni-leipzig.de>"]
license = "BSD3"

[tool.poetry.dependencies]
python = "^3.7.1"
scikit-learn = "^0.24.1"
pandas = "^1.2.1"
joblib = "^1.0.0"
numpy = "^1.20.0"
tqdm = "^4.56.0"
scipy = "^1.6.0"
ngt = "^1.12.2"
annoy = "^1.17.0"
nmslib = "^2.1.1"
importlib-metadata = "^4.5.0;python_version<3.8"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.4"
mypy = "^0.800"
darglint = "^1.6.0"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
tox = "^3.21.4"
black = "^21.6b0"
pyproject-flake8 = "^0.0.1-alpha.2"
flake8-eradicate = "^1.0.0"
flake8-isort = "^4.0.0"
flake8-docstrings = "^1.6.0"
flake8-debugger = "^4.0.0"
flake8-comprehensions = "^3.5.0"
flake8-print = "^4.0.0"
Sphinx = "^4.0.2"
insegel = "^1.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
ignore = "E203, E266, E501, W503, F403, F401, B950"
max-line-length = 88
max-complexity = 18
select = "B,C,E,F,W,T4,B9"
count = "true"
show-source = "true"
statistics = "true"

[tool.black]
line-length = 88
experimental-string-processing = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
