
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T19:23:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "91f97b0ee987be263cb572061eca956f95321a48",
 "version": "2021.07.22-0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
