[tool.poetry]
name = "EzStore"
version = "0.1.0"
description = ""
authors = ["Roni Sundstrom <ronttipontti.sundstrom2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
