[tool.poetry]
name = "typetest"
version = "0.1.1"
description = "Test your typing speed without leaving the terminal."
authors = ["MasterMedo <mislav.vuletic@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
blessed = "^1.18.1"
pandas = "^1.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
typetest = 'typetest.__main__:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
