
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-07-16T20:39:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d72e149ceb0a8b06aba7bf7d8d6ffcca06d4476",
 "version": "0.13.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
