
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T19:47:56+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "27958c66034f277bf820c23fdf6fa44f161f4053",
 "version": "2.6.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
