[tool.poetry]
name = "minichat"
version = "1.0.0"
description = "Mini chatbot client based on AIML"
authors = ["DevAndromeda <devandromeda@snowflakedev.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
python-aiml = "0.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
