[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "dategen"
author = "Chang-Ming Chen"
author-email = "changming.chen.1970@gmail.com"
home-page = "https://codeberg.org/cmc/dategen"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

