[tool.poetry]
name = "eventipy"
version = "2.1.0"
description = "In-memory python event library"
authors = ["Jonatan Martens <jonatanmartenstav@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
pydantic = "1.8.2"

[tool.poetry.dev-dependencies]
pytest = "6.2.1"
Sphinx = "3.4.3"
sphinx-rtd-theme = "^0.5.2"
coveralls = "2.2.0"
pytest-asyncio = "0.14.0"
bump2version = "1.0.1"
black = "21.7b"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
