[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = 'typings/'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --cov --cov-report term"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["setup.py", "tests/*"]

[tool.coverage.xml]
output = "cov.xml"
