
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-18T20:39:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1cbd8fcdb314e7cfaf8e3cd6dccc8b7d11cccc07",
 "version": "v0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
