
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.0'
version_full = '5bd9a2e9a4315c4cfc34ee68564480f906dbb195'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

