from . import DEFAULT_CACHE as DEFAULT_CACHE
from typing import Any

class Cache:
    log: Any
    dir: Any
    data: Any
    def __init__(self, cache_dir: str = ...) -> None: ...
    def save(self) -> None: ...
    def load(self) -> None: ...
    def clean(self) -> None: ...
    def get(self, key: str) -> dict: ...
