from .query_engine import QueryEngine as QueryEngine
from typing import Optional

class ClassDataEngine(QueryEngine):
    def get_classes(self, should_print: bool = ...) -> Optional[dict]: ...
    def get_class(self, class_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_class_media(self, class_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_class_pvp_talent_slots(self, class_id: int, should_print: bool = ...) -> Optional[dict]: ...
