from typing import Any, Optional
from vbinds.enums import IconSize as IconSize
from vbinds.icons import get_icon as get_icon

class IconCache:
    log: Any
    dir: Any
    data: Any
    def __init__(self, icon_dir: str) -> None: ...
    def get(self, name: str, size: IconSize = ...) -> Optional[str]: ...
    def has(self, name: str, size: IconSize = ...) -> bool: ...
    def clean(self) -> None: ...
    def load(self) -> None: ...
