from .query_engine import QueryEngine as QueryEngine
from typing import Optional

class SpecDataEngine(QueryEngine):
    def get_specs(self, should_print: bool = ...) -> Optional[dict]: ...
    def get_spec(self, spec_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_spec_media(self, spec_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_talents(self, should_print: bool = ...) -> Optional[dict]: ...
    def get_spell(self, spell_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_spell_media(self, spell_id: int, should_print: bool = ...) -> Optional[dict]: ...
    def get_talent(self, talent_id: int, should_print: bool = ...) -> Optional[dict]: ...
