
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T12:29:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c17cd17eba4ca44a42482476d98677c81cc0377b",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
