
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T04:06:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "68bde0d8376444efca68d1269db282ea16beb25a",
 "version": "1.15.0.post.dev225"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
