
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T11:15:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cc7ac996f8c6d17e9bfd5cf5362793742fa34ae",
 "version": "0.7.0.post.dev268"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
