
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T17:20:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "18dfebc4b30ce48ac966631bc5de30b6e889fbf4",
 "version": "2.2.12.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
