
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T09:21:51-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b6dcdd2d8de309d9df7cce9e7c1d62616f53959d",
 "version": "2.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
