
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:16:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "daa20b5fac75e140284a3705f6f3b6d644ab1f67",
 "version": "0.7.0.post.dev270"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
