#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['airflow_provider_nessie',
 'airflow_provider_nessie.hooks',
 'airflow_provider_nessie.operators']

package_data = \
{'': ['*'], 'airflow_provider_nessie': ['example_dags/*', 'sensors/*']}

install_requires = \
['pynessie==0.8.3']

entry_points = \
{'apache_airflow_provider': ['provider_info = '
                             'airflow_nessie_provider.__init__:get_provider_info']}

setup(name='airflow-provider-nessie',
      version='0.1.2',
      description='Entry point for the Nessie Airflow provider.',
      author='Project Nessie',
      author_email='nessie-release-builder@dremio.com',
      url='https://github.com/projectnessie/nessie_provider',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
