
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T10:04:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f856a1fd4c219a2439955397186096d1d0b1af5",
 "version": "2021.07.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
