
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T00:24:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16b1c73fcb9427d81cb139eacd8106795c2bb407",
 "version": "0.0.44"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
