
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-17T18:40:37-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7840844030503651e763dee923094e18f19134f",
 "version": "2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
