
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T10:52:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "32b7bb7c9cf264ae7726ee1a03eb516564738521",
 "version": "1.4.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
