
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T11:58:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e9a1defc5d227fc81175a30fca4e1dde21135dcd",
 "version": "0.7.0.post.dev300"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
