
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T12:22:47+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f8ca235faa4b602f0c8ec15fbe881f068339d355",
 "version": "1.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
