
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T03:54:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4b708a2572f361941571d5695bfedfc56380107",
 "version": "1.15.0.post.dev205"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
