
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T17:45:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b108a80627c76707c198c7a7f5ee579847076c96",
 "version": "0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
