"""Functional Programming tools for Python."""
from libfuncpy.lib import (
    ITE,
    ITEX,
    chainf,
    chainfs,
    consume,
    context_engine,
    f1f2,
    f2f1,
    false,
    flatlist,
    give,
    if_elif_else,
    is_none,
    is_not_none,
    ite,
    itev,
    make_iterable,
    mapc,
    none,
    pass_,
    raise_,
    reduce_helper,
    ternary_operator,
    ternary_operator_v,
    ternary_operator_x,
    true,
    vartial,
    whileloop,
    )


__all__ = [
    'ITE',
    'ITEX',
    'chainf',
    'chainfs',
    'consume',
    'context_engine',
    'f1f2',
    'f2f1',
    'false',
    'flatlist',
    'give',
    'if_elif_else',
    'is_none',
    'is_not_none',
    'ite',
    'itev',
    'make_iterable',
    'mapc',
    'none',
    'pass_',
    'raise_',
    'reduce_helper',
    'ternary_operator',
    'ternary_operator_v',
    'ternary_operator_x',
    'true',
    'vartial',
    'whileloop',
    ]

__version__ = '0.0.4'
