# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/tensorflow_metadata/paths.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/tensorflow_metadata/paths.proto',
  package='tecton_proto.tensorflow_metadata',
  syntax='proto2',
  serialized_options=b'\n\036com.tecton.tensorflow_metadataP\001',
  serialized_pb=b'\n,tecton_proto/tensorflow_metadata/paths.proto\x12 tecton_proto.tensorflow_metadata\"\x1a\n\x04Path\x12\x12\n\x04step\x18\x01 \x03(\tR\x04stepB\"\n\x1e\x63om.tecton.tensorflow_metadataP\x01'
)




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='tecton_proto.tensorflow_metadata.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='step', full_name='tecton_proto.tensorflow_metadata.Path.step', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='step', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['Path'] = _PATH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'tecton_proto.tensorflow_metadata.paths_pb2'
  # @@protoc_insertion_point(class_scope:tecton_proto.tensorflow_metadata.Path)
  })
_sym_db.RegisterMessage(Path)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
