
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T07:35:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f68796ec5fc4929d510c29715db65b5c8115282",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
