[tool.poetry]
name = "gachi"
version = "2.0"
description = "No description"
authors = ["Anonymous <anal@gadgets.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyglet = "^1.5.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
