[tool.poetry]
name = "aiohttp-sqlalchemy"
version = "0.32.0"
description = "SQLAlchemy 1.4 / 2.0 support for aiohttp."
authors = [
    "Ruslan Ilyasovich Gilfanov <ri.gilfanov@yandex.ru>",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    # "Framework :: aiohttp",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
keywords = ["aiohttp", "sqlalchemy", "asyncio"]
license = "MIT License"
readme = "README.rst"

documentation = "https://aiohttp-sqlalchemy.readthedocs.io/"
repository = "https://github.com/ri-gilfanov/aiohttp-sqlalchemy"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.7.4.post0"
aiohttp-things = ">=0.13.0"
SQLAlchemy = "^1.4.21"
sqlalchemy-things = ">=0.10.0"
aiomysql = { version = ">=0.0.21", optional = true }
aiosqlite = { version = ">=0.17.0", optional = true }
asyncpg = { version = ">=0.23.0", optional = true }

[tool.poetry.extras]
mysql = ["aiomysql"]
postgresql = ["asyncpg"]
sqlite = ["aiosqlite"]

[tool.poetry.dev-dependencies]
aiosqlite = ">=0.17.0"
flake8 = ">=3.9.2"
isort = ">=5.9.2"
mypy = ">=0.910"
pytest = ">=6.2.4"
pytest-cov = ">=2.12.1"
Sphinx = ">=4.1.1"
sphinx_rtd_theme = ">=0.5.2"
types-toml = ">=0.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = ["aiohttp_sqlalchemy"]
known_third_party = ["aiohttp", "aiohttp-things", "sqlalchemy"]
profile = "wemake"
src_paths = ["aiohttp_sqlalchemy", "examples", "tests"]

[tool.mypy]
files = [
    "aiohttp_sqlalchemy",
    "tests",
]
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = ['sqlalchemy.*']
ignore_missing_imports = true
