
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T04:01:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "79e2e5241611ea782b82f58cd0770180c0ebab72",
 "version": "1.15.0.post.dev217"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
