
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T13:00:04+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5a544d5ed161609689cdc69be5565d65a6e12e8",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
