[tool.poetry]
name = "configur"
version = "0.1.1"
description = "TOML-based configuration for Python"
authors = ["Ryan Whitten <rw@heyrw.dev>"]
license = "MIT"
packages = [
    { include = "configur" },
]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.18.4"
python-box = "^5.3.0"
tomlkit = "^0.7.2"
python-dotenv = "^0.18.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
