
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T18:54:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3e28d43d65ed2ef693ced2b0636b8a4894a5a88",
 "version": "0.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
