[tool.poetry]
name = "capsule_downloader"
version = "0.1.0"
description = "A tool to help users easily download capsules from aotu.ai"
authors = ["Stephen Li <stephen@aotu.ai>"]
license = "Proprietary"

[tool.poetry.dependencies]
python = ">=3.6.6.2,<4.0"
beautifulsoup4 = "^4.9.3"
wget = "^3.2"
requests = "^2.26.0"
lxml = "^4.6.3"
PyInquirer = "^1.0.3"

[tool.poetry.scripts]
capsule_downloader = 'capsule_downloader:main'

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
