
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-18T22:22:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8529ee71e341d4b59e48628d325cd893d3c8ab45",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
