# Generated by Django 3.2.5 on 2021-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('francedata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communedata',
            name='unique commune data',
        ),
        migrations.RemoveConstraint(
            model_name='departementdata',
            name='unique departement data',
        ),
        migrations.RemoveConstraint(
            model_name='epcidata',
            name='unique epci data',
        ),
        migrations.RemoveConstraint(
            model_name='regiondata',
            name='unique region data',
        ),
        migrations.AddConstraint(
            model_name='communedata',
            constraint=models.UniqueConstraint(fields=('commune', 'year', 'datacode'), name='fd_unique_commune_data'),
        ),
        migrations.AddConstraint(
            model_name='departementdata',
            constraint=models.UniqueConstraint(fields=('departement', 'year', 'datacode'), name='fd_unique_departement_data'),
        ),
        migrations.AddConstraint(
            model_name='epcidata',
            constraint=models.UniqueConstraint(fields=('epci', 'year', 'datacode'), name='fd_unique_epci_data'),
        ),
        migrations.AddConstraint(
            model_name='regiondata',
            constraint=models.UniqueConstraint(fields=('region', 'year', 'datacode'), name='fd_unique_region_data'),
        ),
    ]
