# Version file autogenerated by the build process
version = '0.8.0rc2'
build = '681'
vcs_info = 'Git SHA1 3bba9728 committed on 2021-07-20'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.8.0rc2"\nKSCONF_BUILD="681"\nKSCONF_VCS_INFO="Git SHA1 3bba9728 committed on 2021-07-20"')
