name: nr.utils.re
version: 0.3.1
description: This module provides some utility functions for applying regular expressions.
requirements:
- python ^3.6
test-requirements:
- pytest
test-driver:
  type: pytest
typed: true
