[tool.poetry]
name = "summa_pkg"
version = "0.1.0"
description = ""
authors = ["romansnetkov <snetkov.roman@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
