
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T17:50:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "71c7bef92b0ddf36f627344a26f24abf7b1e5346",
 "version": "5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
