
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T11:31:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1ffee53b04a9e2ea426faf568352a7608d51452",
 "version": "0.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
