# Generated by Django 3.2.5 on 2021-07-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatableview_user_columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatableusercolumns',
            options={'verbose_name': 'Datatable user defined columns', 'verbose_name_plural': "Datatable user defined columns's"},
        ),
        migrations.AlterField(
            model_name='datatableusercolumns',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
