# Generated by Django 2.2.9 on 2020-04-08 02:30

import filedepot.models as filedepot_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chunks_directory', models.FilePathField(blank=True, max_length=1024, null=True, path=filedepot_models.file_depot_base_path)),
                ('is_complete', models.BooleanField(default=False)),
                ('flow_filename', models.CharField(max_length=255)),
                ('flow_total_chunks', models.PositiveIntegerField()),
                ('flow_chunk_size', models.PositiveIntegerField()),
                ('flow_total_size', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
