[tool.poetry]
name = "madan"
version = "0.1.0"
description = "Open source ai library"
authors = ["MadanBaduwal <madanbaduwal100@gmail.com>"]

readme = "README.md"
homepage = "https://github.com/MadanBaduwal/madan"

repository = "https://github.com/MadanBaduwal/madan"

documentation = "https://github.com/MadanBaduwal/madan/wiki"

keywords = ["math", "machine learning", "computer vision","natural language processing","madan"]


packages = [
    { include = "madan" }
]
[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^0.84.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
