
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T11:37:44+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "6341c2678309ceb09a8cb55754ec1185341eb6e2",
 "version": "1.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
