[tool.poetry]
name = "drf-rw-serializers-stubs"
version = "1.0.4"
description = "Type stubs for the drf-rw-serializers package"
repository = "https://github.com/benesch/drf-rw-serializers-stubs"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include = "drf_rw_serializers-stubs" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
isort = "^5.9.2"
djangorestframework-types = "^0.6.0"
djangorestframework = "^3.12.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
