
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T12:03:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f94eccf13e3e597f8007a326a2a845494f07f02c",
 "version": "0.0.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
