[tool.poetry]
name = "deviant"
version = "1.1.1"
description = "Модуль для работы с Deviant Api"
authors = ["Deviant <darsox.anime@gmail.com>"]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/DarsoX/Deviant"
homepage = "https://github.com/DarsoX/Deviant/wiki/Documentation-Deviant"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
