
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:25:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccd00dcf4082f5c4aa30393e5f22e30f5718b3c4",
 "version": "6.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
