
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T14:14:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac283281e60b806483a54adf0829e9076f557d13",
 "version": "1.4.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
