[tool.poetry]
name = "deviant"
version = "0.0.9"
description = "Модуль для работы с Deviant Api"
authors = ["Deviant <darsox.anime@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
