[tool.poetry]
name = "legion-cli"
version = "0.1.6"
description = "Commandline Utilities for the Legion Alerting and Monitoring System"
authors = ["Eugene Kovalev <eugene@kovalev.systems>"]
classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
]
documentation="https://gitlab.com/legion-robotnik/legion-cli"
repository="https://gitlab.com/legion-robotnik/legion-cli"
readme="README.md"
license="GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0"
pyyaml = "^5.4.1"
pydantic = "^1.7.3"
typeguard = "^2.1.0"
logzero = "^1.6.3"
robotnikmq = "^0.2.0"
legion-utils = "^0.1"
termcolor = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"

[tool.poetry.scripts]
legion = 'legion_cli.cli:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
