
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T11:17:54+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5159162fce831a52f58bc2eb8196aa3d51ed0189",
 "version": "0.7.0.post.dev256"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
