
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:43:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e903b955c62e502a731ab278c99bacc0e70f234",
 "version": "0.7.0.post.dev274"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
