[tool.poetry]
name = "pylista"
version = "0.1.0"
description = "A simple CLI tool to manage lists"
authors = ["Herson Oliveira <oliveira.herson@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^6.2.4"
tox = "^3.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pylista = "pylista.cli:cli"
