[tool.poetry]
name = "Marsworks"
version = "0.2.1"
description = "An Async. API Wrapper around NASA's Mars Photos API written in Python."
authors = ["NovaEmiya <importz750@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
