
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T08:33:19+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "971e3523cb273f16cc2afd3659b80723afffd6ab",
 "version": "0.2.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
