
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T01:55:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "61ce4e6045092614c494da4d65165911110951a2",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
