
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T14:43:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "69810194b996c167c03b6b2fdce0b96fb5154494",
 "version": "0.12.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
