
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T12:28:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a39bb897888b0c737038566b9fc15c1e6303885",
 "version": "0.7.0.post.dev282"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
