#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['binpickle', 'binpickle.codecs']

package_data = \
{'': ['*']}

install_requires = \
['msgpack >= 1.0']

extras_require = \
{":python_version < '3.8'": ['pickle5'],
 'blosc': ['blosc'],
 'dev': ['flake8', 'rstcheck'],
 'doc': ['sphinx'],
 'numcodecs': ['numcodecs >= 0.7'],
 'test': ['pytest >= 5',
          'pytest-cov',
          'hypothesis >= 6',
          'pandas >= 1.0',
          'numpy >= 1.17']}

setup(name='binpickle',
      version='0.3.4',
      description='Optimized format for pickling binary data.',
      author='Michael Ekstrand',
      author_email='michaelekstrand@boisestate.edu',
      url='https://binpickle.lenskit.org',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>= 3.6.1',
     )
