# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_s3_key_list": "25_s3_cmd.ipynb",
         "s3_session": "25_s3_cmd.ipynb",
         "s3": "25_s3_cmd.ipynb",
         "bucket": "25_s3_cmd.ipynb",
         "df": "25_s3_cmd.ipynb",
         "list_s3_files": "25_s3_cmd.ipynb",
         "files_df": "25_s3_cmd.ipynb"}

modules = ["s3.py"]

doc_url = "https://jakubLangr.github.io/mlt/"

git_url = "https://github.com/jakubLangr/mlt/tree/{branch}/"

def custom_doc_links(name): return None
