
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T08:31:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "792ec4069074ed327a0bf540c8f38afe41109902",
 "version": "2021.7.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
