"""
    Delphix API Gateway

    Delphix API Gateway API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.api_key_token import ApiKeyToken


class TestApiKeyToken(unittest.TestCase):
    """ApiKeyToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKeyToken(self):
        """Test ApiKeyToken"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKeyToken()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
