
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:54:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4270ed5ed984e6e19a75ac26124f9ff8b75feddf",
 "version": "0.7.0.post.dev276"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
