
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T11:15:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ed60a5cb8684001e5def33ab5c5f3a1108d98f1",
 "version": "0.7.0.post.dev306"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
