[tool.poetry]
name = "darbiadev-sanmar"
version = "0.1.0"
description = ""
authors = ["Bradley Reynolds <bradley.reynolds@darbia.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
suds-community = "^0.8.5"
xmltodict = "^0.12.0"
python-benedict = "^0.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
