[tool.poetry]
name = "3y"
version = "0.1.0"
description = ""
authors = ["child"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0","beginnings","pdsystem"]
build-backend = "poetry.core.masonry.api"
