
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "07a93b0bfc4b5756c53d825532a7e6dd6cafbf0b",
 "version": "1.8.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
