[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "assm"
author = "Alexander Popov"
author-email = "iiiypuk@iiiypuk.me"
home-page = "https://github.com/emilecok/assm"
requires = ["Pillow==8.3.1" ]
description-file = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3"
]
requires-python = ">=3"
keywords = "iOS,splashscreen,splash-screen"

[tool.flit.metadata.requires-extra]
dev = ["pylint == 2.7.1", "black == 20.8b1"]

[tool.flit.metadata.urls]
Documentation = "https://docs/"

[tool.black]
line-length = 99
