#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['assm']

package_data = \
{'': ['*']}

install_requires = \
['Pillow==8.3.1']

extras_require = \
{'dev': ['pylint == 2.7.1', 'black == 20.8b1']}

setup(name='assm',
      version='0.1.2',
      description='iOS splash screen generator',
      author='Alexander Popov',
      author_email='iiiypuk@iiiypuk.me',
      url='https://github.com/emilecok/assm',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3',
     )
