[tool.poetry]
name = "teppan"
version = "0.2.alpha.1"
description = "Teppan is integrated for Sinopac Trading API - Shioaji."
authors = ["yp0chien <ypochien@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
shioaji = "^0.3.2.dev4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
