
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T17:55:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6559f9976686c06098aca052a0f86d3d116706c",
 "version": "0.0.10rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
