
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-17T18:19:44+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "b251a76b8f30a69633b0bade52b4fed6ac5a5330",
 "version": "0.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
