
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-16T07:27:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f46eb89c0502c770f0edc8ebe8eecdec2456fa71",
 "version": "1.82.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
