language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
branches:
  only:
    - main
cache: pip
install: pip3 install -r requirements_dev.txt
script: tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
