#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sqlatracker']

package_data = \
{'': ['*']}

setup(name='sqlatracker',
      version='0.0.7',
      description='trace your model field change log',
      author='Ed__xu__Ed',
      author_email='m.tofu@qq.com',
      url='https://github.com/Ed-XCF/sqlatracker',
      packages=packages,
      package_data=package_data,
     )
