# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2021-07-19T19:55:10.027402'

__version__ = '2021.7'
__sha__ = '418904a272bbf624a0c82f9aaffd1bc36377b493'
__revision__ = '418904a272bbf624a0c82f9aaffd1bc36377b493'
