
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T11:26:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "418904a272bbf624a0c82f9aaffd1bc36377b493",
 "version": "2021.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
