
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T13:09:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6aaf8577ac2cdeee6401d68a63eefc724e1087d7",
 "version": "1.15.0.post.dev245"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
