
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T18:12:43+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1fcce50c138f15e58c4082233e7808a5bdbae0d4",
 "version": "2.6.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
