[tool.poetry]
name = "injectark"
version = "0.7.2"
description = "Dependency Injector for Python"
authors = ["eecheverry <eecheverry@nubark.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
