#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mypy_test']

package_data = \
{'': ['*']}

install_requires = \
['mypy', 'lxml']

extras_require = \
{'test': ['pytest']}

entry_points = \
{'console_scripts': ['mypy_test = mypy_test:entrypoint']}

setup(name='mypy-test',
      version='0.1.1',
      description='Test mypy plugins, stubs, custom types.',
      author='Gram',
      author_email='gram@orsinium.dev',
      url='https://github.com/orsinium-labs/mypy_test',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
