from blackdogosint.utils.data import *

def get_supportedengines() -> Set[Union[str, Any]]:
    return {'anubis',
            'baidu',
            'binaryedge',
            'bing',
            'bingapi',
            'bufferoverun',
            'censys',
            'certspotter',
            'crtsh',
            'dnsdumpster',
            'duckduckgo',
            'github-code',
            'google',
            'hackertarget',
            'hunter',
            'intelx',
            'linkedin',
            'linkedin_links',
            'netcraft',
            'omnisint',
            'otx',
            'pentesttools',
            'projectdiscovery',
            'qwant',
            'rapiddns',
            'rocketreach',
            'securityTrails',
            'sublist3r',
            'spyse',
            'threatcrowd',
            'threatminer',
            'trello',
            'twitter',
            'urlscan',
            'virustotal',
            'yahoo',
            'zoomeye'
            }