
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T11:27:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "88f0a0e50b92b3786682b656407fad75a232d2b2",
 "version": "0.7.0.post.dev308"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
