#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['mdurl']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='mdurl',
      version='0.0.1',
      description='Markdown URL utilities',
      author=None,
      author_email='Taneli Hukkinen <hukkin@users.noreply.github.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.6',
     )
