
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T13:05:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "43423b676b0b68a90a81bd151ece9e557885cdc0",
 "version": "1.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
