stages:
  - image
  - test
  - integration
  - build
  - publish

#############
# templates #
#############
.job:
  image: $CI_REGISTRY/linaro/tuxrun/ci
  script:
  - make $CI_JOB_NAME

######
# CI #
######
ci-image:
  stage: image
  image: docker:20.10-dind
  services:
  - name: docker:20.10-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
  - 'docker build -t $CI_REGISTRY/linaro/tuxrun/ci -f Dockerfile.ci .'
  - 'docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY'
  - 'docker push $CI_REGISTRY/linaro/tuxrun/ci'
  only:
    refs:
    - master
    changes:
    - Dockerfile.ci

########
# test #
########
unit-tests:
  extends: .job
  stage: test

stylecheck:
  extends: .job
  stage: test

typecheck:
  extends: .job
  stage: test

spellcheck:
  extends: .job
  stage: test

###############
# integration #
###############
integration:
  extends: .job
  image: lavasoftware/lava-dispatcher:latest
  stage: integration
  before_script:
  - apt-get update
  - apt-get install --yes linux-image-amd64
  script:
  - PYTHONPATH=. python3 test/integration.py --runtime null --device $DEVICE --tests $TEST
  parallel:
    matrix:
    - DEVICE:
      - qemu-armv5
      - qemu-armv7
      - qemu-arm64
      - qemu-i386
      - qemu-mips32
      - qemu-mips32el
      - qemu-mips64
      - qemu-mips64el
      - qemu-ppc64
      - qemu-ppc64le
      - qemu-riscv64
      - qemu-sparc64
      - qemu-x86_64
      TEST:
      - ltp-fcntl-locktests ltp-fsx ltp-fs_perms_simple ltp-smoke
      - ltp-fs_bind
      - ltp-nptl
  only:
    refs:
    - master

#########
# Build #
#########
doc:
  extends: .job
  stage: build
  artifacts:
    paths:
      - public
  before_script:
    - python3 -m pip install mkdocs-material  # FIXME not in Debian

###########
# publish #
###########
pages:
  extends: .job
  stage: publish
  needs:
    - doc
  artifacts:
    paths:
      - public
  only:
    - tags
  script:
    - 'true' # nothing to do

publish-pypi:
  extends: .job
  stage: publish
  only:
    - tags
