
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T12:04:55+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "74c9c9f4dc95f53e6415731fda54475402e5b5fe",
 "version": "0.7.0.post.dev266"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
