
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T16:12:55+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc81dc0afdd9a89e60513217e018c1407ed4bbbd",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
