
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T11:32:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c4a2bd88674bc81d3cb08cbbc816e3b629b435c8",
 "version": "0.7.0.post.dev294"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
