# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install flit
    - name: Get version
      run: |
        echo "\"\"\"trace your model field change log\"\"\"" > sqlatracker/__init__.py
        echo $GITHUB_REF | awk -F '/' '{print "__version__=\""$3"\""}' >> sqlatracker/__init__.py
    - name: Build and publish
      env:
        FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
        FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        flit publish
