
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.54.0rc2'
version_full = 'c3fb39834e677ff2501d51acc8c33e105980f995'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

