input: ["none"]
output: ["img", "pipeline_end", "filename", "fps"]

resize: {
            do_resizing: False,
            width: 1280,
            height: 720
        }
input_dir: 'PeekingDuck/data/input'
mirror_image: False