[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ikea_api"
author = "vrslev"
author-email = "5225148+vrslev@users.noreply.github.com"
home-page = "https://github.com/vrslev/ikea-api-client"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]
description-file = "README.md"
requires-python = ">=3.7"
requires = ["aiohttp>=3.7.4", "requests>=2.26.0", "brotli>=1.0.9", "bs4>=0.0.1"]

[tool.flit.sdist]
exclude = ["response_examples"]

[tool.black]
target-version = ["py37"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
include_trailing_comma = true
line_length = 79

[tool.pyright]
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownParameterType = false
reportUnknownLambdaType = false
