#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['ikea_api',
 'ikea_api.endpoints',
 'ikea_api.endpoints.cart',
 'ikea_api.endpoints.item',
 'ikea_api.endpoints.order_capture',
 'ikea_api.endpoints.purchases']

package_data = \
{'': ['*']}

install_requires = \
['aiohttp>=3.7.4', 'requests>=2.26.0', 'brotli>=1.0.9', 'bs4>=0.0.1']

setup(name='ikea_api',
      version='0.1.6',
      description='IKEA API Client',
      author='vrslev',
      author_email='5225148+vrslev@users.noreply.github.com',
      url='https://github.com/vrslev/ikea-api-client',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
