[build-system]
requires = ["setuptools>=56", "wheel", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[pytest.enabler.black]
addopts = "--black"

[pytest.enabler.cov]
addopts = "--cov"