# Generated by Django 3.2.5 on 2021-07-18 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('system_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('parent_system_id_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('parent_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='djangostatuspage.system')),
            ],
            options={
                'ordering': ('parent_system_id_path', 'rank', 'name', 'system_id'),
            },
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['system_id'], name='djangostatu_system__cfaa04_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['parent_system_id_path'], name='djangostatu_parent__e75588_idx'),
        ),
    ]
