# Generated by Django 3.2.5 on 2021-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangostatuspage', '0002_auto_20210718_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('rank', 'name', 'system_id')},
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='N', max_length=64),
        ),
    ]
