[tool.poetry]
name = "spyc_spc"
version = "1.1"
description = "Simple tool to help plot SPC data from multiple locations for comparison"
authors = ["fanoway <86997883+fanoway@users.noreply.github.com>"]
readme = "README.md"
homepage="https://github.com/fanoway/spyc"

[tool.poetry.dependencies]
python = "^3.8"
plotly = "^5.1.0"
numpy = "^1.21.0"
pandas = "^1.3.0"
openpyxl = "^3.0.7"
ipywidgets = "^7.6.3"
dash = "^1.20.0"
docopt = "^0.6.2"
mainentry = "^2.0"
cheroot = "^8.5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.6b0"
tox = "^3.23.1"
pytest-cov = "^2.12.1"
mypy = "^0.910"
flake8 = "^3.9.2"
pylint = "^2.9.3"
flake8-docstrings = "^1.6.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
spyc = "spyc_spc.main:main"

[tool.black]
line-length = 79

[tool.tox]
# tox.ini
legacy_tox_ini = """
[tox]
isolated_build = True
isolated_build_env = testenv
envlist = py38, py39

[tox:.package]
# note tox will use the same python version as under what tox is installed to package
# so unless this is python 3 you can require a given python version for the packaging
# environment via the basepython key
basepython = python3

[testenv]
whitelist_externals = poetry

commands =
	poetry run black spyc_spc/
	poetry run flake8 spyc_spc/
	poetry run pylint spyc_spc/ --exit-zero
	poetry run pylint spyc_spc/ -E
	poetry run mypy spyc_spc/
	poetry run pytest --cov=spyc_spc tests/

"""
