[tool.poetry]
name = "marcos-hello-world-package"
version = "0.1.1"
description = "Package to publish to PyPI that says 'Hello World'."
authors = ["Marco Gancitano <marco.gancitano97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
