[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "zandbak"
author = "Arpad Rozsas"
author-email = "rozsasarpi@gmail.com"

[tool.coverage.run]
source = ["zandbak"]
