#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['zandbak', 'zandbak.beams']

package_data = \
{'': ['*']}

setup(name='zandbak',
      version='0.0.1',
      description='A sandbox python repository for testing GitHub features, CI pipelines, and python',
      author='Arpad Rozsas',
      author_email='rozsasarpi@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
     )
