# automatically generated by the FlatBuffers compiler, do not modify
from ctypes import (
    c_int8 as int8,
    c_int32 as int32,
)
from dataclasses import dataclass
from typing import Protocol

from typing import Union

@dataclass
class Email:
    email_from: str
    email_message_id: str

@dataclass
class Comment:
    author_type: int8
    author: "Author"
    date: "DateTime"
    body: str

@dataclass
class Attachment:
    author: "User"
    timestamp: "DateTime"
    body: str

@dataclass
class Task:
    title: str
    created: "Date"
    due: "Date"
    completed: bool
    completed_date: "Date"
    created_by: "User"
    assigned_to: "User"
    note: str
    priority: int32
    comments: "[Comment]"
    attachments: "[Attachment]"

@dataclass
class TaskList:
    name: str
    slug: str
    group: "Group"
    tasks: "[Task]"


Author = Union[User, Email]
