
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T11:46:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4d5bd937d0a82fb957facd6bd0c9be79617e321",
 "version": "0.7.0.post.dev262"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
