#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['gslibutils']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['typer >= 0.3.0', 'numpy >= 1.19.0', 'pandas >= 1.3.0']

extras_require = \
{'all': ['colorama >=0.4.3,<0.5.0', 'shellingham >=1.3.0,<2.0.0'],
 'dev': ['autoflake >=1.3.1,<2.0.0', 'flake8 >=3.8.3,<4.0.0'],
 'doc': ['mkdocs >=1.1.2,<2.0.0',
         'mkdocs-material >=5.4.0,<6.0.0',
         'markdown-include >=0.5.1,<0.6.0'],
 'test': ['pytest >=4.4.0,<5.4.0',
          'pytest-cov >=2.10.0,<3.0.0',
          'coverage >=5.2,<6.0']}

setup(name='gslibutils',
      version='0.1.0',
      description='Contains utilities to load/save GSLIB files, such as',
      author='Exequiel Sepúlveda',
      author_email='esepulveda@protonmail.com',
      url='https://github.com/exepulveda/gslibutils',
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.6',
     )
