[tool.poetry]
name = "cfpm"
version = "0.0.0"
description = "The C-Family Package Manager."
license = "MIT"
authors = ["Yi Cao <caoyi06@qq.com>"]
repository = "https://github.com/project-cfpm/cfpm"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools"
]
packages = [
    { include = "cfpm" },
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/project-cfpm/cfpm/issues"

[tool.poetry.dependencies]
python = "^3.6.2"
click = "^8.0.1"
click-log = "^0.3.2"
tomli = "^1.0.4"
appdirs = "^1.4.4"
semver = "^2.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
mypy = "^0.910"
black = "^21.7b0"
pydocstyle = "^6.1.1"
coverage = "^5.5"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
cfpm = "cfpm.console:cli"
