
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T12:52:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a5e2b32115701ef2d66cc77604a388bed08a983",
 "version": "0.7.0.post.dev288"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
