
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T16:21:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1ba97a5fb78bcf188c18ebc842745045a79443b",
 "version": "0.1.0a22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
