
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T15:58:50+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb6e17eb6b696cf9d99d7e53c48094b9a7dd403e",
 "version": "2.9.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
