
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-19T05:25:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "374e7f12279f3962ae238e88948a3c8555f7e5c1",
 "version": "1.15.0.post.dev211"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
