
language: python
sudo: false
matrix:
  include:
    - python: 3.7.8
      env: TOX_ENV=py37
    - python: 3.8.5
      env: TOX_ENV=py38
    - python: 3.9
      env: TOX_ENV=py39
    - python: 3.7
      env: TOX_ENV=cover
    - python: 3.7
      env: TOX_ENV=style
    - python: 3.7
      env: TOX_ENV=docs
before_install:
  - openssl aes-256-cbc -K $encrypted_12bdf0f74de5_key -iv $encrypted_12bdf0f74de5_iv -in hoshi-gct.json.enc -out hoshi-gct.json -d

install:
  - pip install -U pip wheel
  - pip install tox
cache:
  directories:
    - $HOME/.cache/pip
before_script:
  - uname -a
script:
  - tox -v -e $TOX_ENV
