
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T19:32:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0742a831f9ce98a1b630205e7d59276a9b67e70",
 "version": "0.1.0a6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
