
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T09:52:12-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d0924df3e243508e53a04ec6a9967392f217329",
 "version": "0.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
