
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T15:35:22+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c8081962aea1c005078dc4dacf275ac83b9c0b25",
 "version": "1.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
