
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-06-02T17:31:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6ab1c1eac6bac40ee7fca0d1ef3921aa89c1b36",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
