# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_name": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://PrathamBapat.github.io/hello_name/"

git_url = "https://github.com/PrathamBapat/hello_name/tree/main/"

def custom_doc_links(name): return None
