
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T11:37:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b022e2061e4ab9b3c48059e32ae08cd60b08edf5",
 "version": "2021.07.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
