# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"clahe_img": "core.ipynb",
         "CorrespondenceAnnotator": "core.ipynb",
         "imread": "io.ipynb",
         "load_pts": "io.ipynb",
         "leave_one_out_F_validation": "metrics.ipynb",
         "get_error_stat_string": "metrics.ipynb",
         "get_big_errors_string": "metrics.ipynb"}

modules = ["core.py",
           "io.py",
           "metrics.py"]

doc_url = "https://ducha-aiki.github.io/pixelstitch/"

git_url = "https://github.com/ducha-aiki/pixelstitch/tree/master/"

def custom_doc_links(name): return None
