
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-15T11:56:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6000bfdf348e567caba2e7e427d85c894af510e",
 "version": "0.7.0.post.dev264"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
