language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bdraco
  password:
    secure: gPdacOtAbqDIJarizGDnencthCMuEd8Yyho4MeWr1oAZgq87nRbC8afMMxImx8OeVKw6S3VLeRKUW2GCCtlQkJAwq6JoQyIJMcyaDsyazu+nOW8DiGfTGJmYTSxnhM/xnijxGSf6SdEYnIdFveMLzFVvxmSvyZPO0S1zX3uo6VUIA8wNkWgS5DVH3R/oS+hjnxz5maFdzZ2lEdzegqPjRa7D+IzZomxCOba4H00gyoaGlPgoBv+CdRt+yK2MRuE+DvUQlVMxVAvz5p+kEbOf5DOnngGhejqPO4r+wTZ2czvEY2a//Oii8UWEOQ3/4lWCrMrMXIyuj5UEyAUdMDJqscS5ZTKdvPzOLgRUVmPnfcdQJ8xYJYp8LA0YFeKeidY4M//aSTgIxjg1iczubWEp1rnje4LJBskJ3MRUo5BqOCLxS6Eoai+RbQtTMbJkWUghnpbwxGyQqPVurzxr0sTpYLBLJ7wIhV0i9+uxnD5hemF0ODjA1CCXAUyAr0Ycx2PI+AwO5pkw2XYxZ3f0BouSfxmVmV3tLBZpXNGG84CUNtCAOz93RFjAfweVaojlntx0IYWH4ODR7AufWlPhkebIK4e5uZXxKPItR33WQsfY9QtTI+A08Qhccrij73KnRoEXPjsxNG5GwTk6i/GigzYqp2zFtSCrhj9+aPhycKqybEs=
  on:
    tags: true
    repo: bdraco/nexia
    python: 3.8
after_success:
- coveralls
