
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-21T03:23:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "77f9451eed92b850b5a84bcb05f491cb279d2439",
 "version": "1.15.0.post.dev219"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
