[tool.poetry]
name = "img2cmd"
version = "1.0.0"
description = "Functions: drawimg(depth, image_path) | You must install \"Color-It\" and \"Pillow\" too"
authors = ["Mitikas <mitikas333@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
