
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T15:41:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a63130ab335200f4616af738314be1d6b1438a67",
 "version": "0.9.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
