[tool.poetry]
name = "neo-toolbox"
version = "0.1.3"
description = "Tools for working with the Neo N3 blockchain."
authors = ["Adrian Fjellberg <adrian@adapted.no>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
