
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-18T07:23:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "41c56d8277b99cd2dfc1633f51103401ab2b4145",
 "version": "2021.7.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
