exclude: '^jawanndenn/static/3rdparty/'

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.21.2
    hooks:
      - id: pyupgrade
        args: ['--py38-plus']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: '^jawanndenn/migrations/'

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.2
    hooks:
      - id: isort

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
