
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T13:02:55-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "794fc4da6b1d1060e6b3ada2c1cc2996b0e8b747",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
