
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-22T23:46:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "27abe82cc640ff5dbbb2af94c4fc3ae7e73f574c",
 "version": "0.19.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
