[tool.poetry]
name = "vidoptim"
version = "0.0.1-alpha.3"
description = "ffmpeg backed video optimizer"
authors = ["Nik Cubrilovic <git@nikcub.me>"]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/nc9/vidoptim"
repository = "https://github.com/nc9/vidoptim"

keywords = ["video", "ffmpeg", "export"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Framework :: Scrapy",
  "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"
pydantic = "^1.5.1"
tqdm = "^4.61.1"
ffmpeg-python = "^0.2.0"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.7.8"
isort = "^5.6.4"
pylint = "^2.2"
rope = "^0.18.0"
ipython = "^7.15.0"
pytest = "^6.1.2"
pytest-watch = "^4.2.0"
mypy = "^0.790"
pycodestyle = "^2.6.0"
py-spy = "^0.3.3"
pytest-benchmark = {extras = ["histogram"], version = "^3.2.3"}
pdbpp = "^0.10.2"
pytest-sugar = "^0.9.4"
myst-parser = "^0.13.5"


[tool.poetry.scripts]
vidoptim = 'vidoptim:cli'

[tool.black]
line-length = 99
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
/(\.git/
  |\.eggs
  |__pycache__
  |\.cache
  |\.ipynb_checkpoints
  |\.mypy_cache
  |\.pytest_cache
  |\.tox
  |\.venv
  |node_modules
  |_build
  |buck-out
  |build
  |dist
  |media
  |infrastructure
  |templates
  |locale
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 99

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
