
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-20T14:52:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f670781921acf80805a7d9c913bff0e8e78835f",
 "version": "0.4.31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
